### PR TITLE
Update dependence to lua 5.4

### PR DESCRIPTION
**Pull request by minglangdu**

### CODE REVIEW

**Comment by joe7575** [comment]
Nice work, but why did you change this? What is your intension?
vm16 is mainly used for the Minetest mods beduino and pdp13 and Minetest requires Lua 5.1

**Comment by minglangdu** [comment]
I was going to install vm16 but I ran into many problems with it because it used lua 5.1 and luarocks used lua 5.4

**Comment by joe7575** [comment]
Then try `luarocks make --lua-version 5.1` or `sudo luarocks make --lua-version 5.1`
I changed the readme in the meantime

**Comment by minglangdu** [comment]
okay then, thanks!

**Pull request closed without merging**
